# -*- coding: utf-8 -*-
"""da4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dzREwZ58qw5HAhda5_o6ZLFhshLc3V01
"""
import pandas as pd
import streamlit as st
import plotly.express as px
import plotly.graph_objects as go


st.set_page_config(page_title="Egypt Export Competitiveness", layout="wide")


st.markdown("""
    <style>
    .main-title { font-size:32px !important; font-weight: bold; text-align: center; color: #1E3A8A; margin-bottom: 25px; }
    .section-title { font-size:20px !important; font-weight: bold; color: #2D3748; margin-top: 15px; }
    </style>
    """, unsafe_allow_html=True)

st.markdown('<div class="main-title">🌍 Egypt Export Competitiveness Dashboard</div>', unsafe_allow_html=True)

@st.cache_data 
def load_data():
    data = pd.read_csv('ph4.csv')
    data.columns = data.columns.str.strip()
    return data

df = load_data()

col1, col2 = st.columns(2)

with col1:
    st.markdown('<div class="section-title">1. Total Price Comparison (Base + Tariff)</div>', unsafe_allow_html=True)
    df_sorted_price = df.sort_values(by='Total Price')

    colors_price = ['#d9534f' if x == 'Egypt' else '#5bc0de' for x in df_sorted_price['Compitatores']]
    
    fig1 = px.bar(df_sorted_price, x='Total Price', y='Compitatores', orientation='h',
                  hover_data=['Tariff', 'Distance'],
                  color='Compitatores', color_discrete_sequence=colors_price)
    fig1.update_layout(showlegend=False, height=350, margin=dict(l=20, r=20, t=20, b=20))
    st.plotly_chart(fig1, use_container_width=True)

with col2:
    st.markdown('<div class="section-title">2. Geographical Distance to Market</div>', unsafe_allow_html=True)
    df_sorted_dist = df.sort_values(by='Distance')
    colors_dist = ['#d9534f' if x == 'Egypt' else '#f0ad4e' for x in df_sorted_dist['Compitatores']]
    
    fig2 = px.bar(df_sorted_dist, x='Distance', y='Compitatores', orientation='h',
                  hover_data=['Total Price'],
                  color='Compitatores', color_discrete_sequence=colors_dist)
    fig2.update_layout(showlegend=False, height=350, margin=dict(l=20, r=20, t=20, b=20))
    st.plotly_chart(fig2, use_container_width=True)



col3, col4 = st.columns(2)

with col3:
    st.markdown('<div class="section-title">3. Tariff Rates by Country</div>', unsafe_allow_html=True)
    df_sorted_tariff = df.sort_values(by='Tariff')
    colors_tariff = ['#d9534f' if x == 'Egypt' else '#5cb85c' for x in df_sorted_tariff['Compitatores']]
    
    fig3 = px.bar(df_sorted_tariff, x='Tariff', y='Compitatores', orientation='h',
                  labels={'Tariff': 'Tariff (%)'},
                  color='Compitatores', color_discrete_sequence=colors_tariff)
    fig3.update_layout(showlegend=False, height=350, margin=dict(l=20, r=20, t=20, b=20))
    st.plotly_chart(fig3, use_container_width=True)

with col4:
    st.markdown('<div class="section-title">4. Market Position: Distance vs Total Price</div>', unsafe_allow_html=True)
    
    fig4 = px.scatter(df, x='Distance', y='Total Price', 
                      color='Trade Agreements', 
                      size='Tariff',
                      hover_name='Compitatores',
                      color_discrete_map={'Yes': '#5cb85c', 'No': '#d9534f'},
                      size_max=40, opacity=0.7)  # تعديل alpha إلى opacity
    
    egypt = df[df['Compitatores'] == 'Egypt']
    if not egypt.empty:
        fig4.add_trace(go.Scatter(
            x=egypt['Distance'], y=egypt['Total Price'],
            mode='markers',
            marker=dict(color='purple', size=25, line=dict(color='black', width=2)),
            name='Egypt (Target)',
            hovertext=f"Egypt<br>Price: {egypt['Total Price'].values[0]}<br>Distance: {egypt['Distance'].values[0]}"
        ))
        
    fig4.update_layout(height=350, margin=dict(l=20, r=20, t=20, b=20), legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
    st.plotly_chart(fig4, use_container_width=True)





