# -*- coding: utf-8 -*-
"""da2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvzRgf7riZ8iBhEoqtsJ6ZwJr-otw6-_
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go


st.set_page_config(
    page_title="Phase 2: ME Market Intelligence",
    page_icon="🧪",
    layout="wide",
    initial_sidebar_state="expanded"
)


st.markdown("""
    <style>
    .main {
        background-color: #f8fafc;
    }
    .metric-card {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 12px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
        border: 1px solid #e2e8f0;
        text-align: center;
    }
    .metric-val {
        font-size: 28px;
        font-weight: bold;
        color: #1e3a8a;
    }
    .metric-lbl {
        font-size: 14px;
        color: #64748b;
        margin-top: 5px;
    }
    .stTabs [data-baseweb="tab-list"] {
        gap: 8px;
    }
    .stTabs [data-baseweb="tab"] {
        background-color: #f1f5f9;
        border-radius: 8px 8px 0px 0px;
        padding: 10px 20px;
        color: #475569;
        font-weight: 600;
    }
    .stTabs [aria-selected="true"] {
        background-color: #1e3a8a !important;
        color: white !important;
    }
    </style>
""", unsafe_allow_html=True)


st.title("🔬 Phase 2: Middle East Target Market Identification")
st.markdown(" Hydrogen Peroxide Market Analysis")
st.write("---")


@st.cache_data
def load_data(file_source):
    try:
        df = pd.read_csv(file_source, encoding='unicode_escape')
        df.columns = df.columns.str.strip()
        return df
    except Exception as e:
        st.error(f"❌ An error occurred while reading the file: {e}")
        return None

st.sidebar.header("📁 Data Source")
uploaded_file = st.sidebar.file_uploader("Upload 'Py Project.csv' here", type=["csv"])

file_path = uploaded_file if uploaded_file is not None else "Py Project.csv"

df_raw = load_data(file_path)

if df_raw is not None:

    df_me = df_raw[df_raw['Region'].str.contains('Middle East', case=False, na=False)].copy()


    med_val = df_me['Value imported in 2024 (USD thousand)'].median()
    med_grow = df_me['Annual growth in value between 2020-2024 (%)'].median()
    med_hhi = df_me['Concentration of supplying countries'].median()


    col1, col2, col3, col4 = st.columns(4)
    with col1:
        total_import = df_me['Value imported in 2024 (USD thousand)'].sum()
        st.markdown(f'<div class="metric-card"><div class="metric-val">${total_import:,.0f}K</div><div class="metric-lbl">Total ME Market Size (2024)</div></div>', unsafe_allow_html=True)
    with col2:
        avg_growth = df_me['Annual growth in value between 2020-2024 (%)'].mean()
        st.markdown(f'<div class="metric-card"><div class="metric-val">{avg_growth:.1f}%</div><div class="metric-lbl">Average ME Annual Growth</div></div>', unsafe_allow_html=True)
    with col3:
        open_markets = len(df_me[df_me['Concentration of supplying countries'] < 0.4])
        st.markdown(f'<div class="metric-card"><div class="metric-val">{open_markets} / {len(df_me)}</div><div class="metric-lbl">Open/Fragmented Markets</div></div>', unsafe_allow_html=True)
    with col4:

        df_me['Is_Top'] = df_me['Value imported in 2024 (USD thousand)'] >= med_val
        df_me['Is_Dynamic'] = df_me['Annual growth in value between 2020-2024 (%)'] >= med_grow
        df_me['Is_Actual'] = df_me['Concentration of supplying countries'] <= med_hhi
        df_me['Criteria_Count'] = df_me['Is_Top'].astype(int) + df_me['Is_Dynamic'].astype(int) + df_me['Is_Actual'].astype(int)
        golden_count = len(df_me[df_me['Criteria_Count'] >= 2])
        st.markdown(f'<div class="metric-card"><div class="metric-val" style="color: #10b981;">{golden_count} Markets</div><div class="metric-lbl">Golden Target Markets (Score ≥ 2)</div></div>', unsafe_allow_html=True)

    st.write("##")


    tabs = st.tabs([
        "📊 Q1: Top Importers",
        "⚡ Q2: Growth Dynamics",
        "🇪🇬 Q3: Egypt Proximity",
        "🎯 Q4: Golden Targets",
        "🔒 Q5: Market Structure (HHI)"
    ])

    # ------------------ TAB 1: Top Importers ------------------
    with tabs[0]:
        st.subheader("Which countries are the top importers of Hydrogen Peroxide?")
        st.markdown("Analysis of total market demand size in the Middle East for the year 2024.")


        fig_q1 = px.bar(
            df_me.sort_values(by='Value imported in 2024 (USD thousand)', ascending=True),
            x='Value imported in 2024 (USD thousand)',
            y='Importers',
            orientation='h',
            color='Value imported in 2024 (USD thousand)',
            color_continuous_scale='Blues',
            labels={'Value imported in 2024 (USD thousand)': 'Import Value (USD Thousand)', 'Importers': 'Country'},
            text_auto='.2s'
        )
        fig_q1.update_layout(height=450, margin=dict(l=20, r=20, t=10, b=10))
        st.plotly_chart(fig_q1, use_container_width=True)

    # ------------------ TAB 2: Growth Dynamics ------------------
    with tabs[1]:
        st.subheader("Which markets show increasing demand and growth potential?")
        st.markdown("Monitoring the most dynamic and growing markets based on the Compound Annual Growth Rate (2020-2024).")

        fig_q2 = px.bar(
            df_me.sort_values(by='Annual growth in value between 2020-2024 (%)', ascending=True),
            x='Annual growth in value between 2020-2024 (%)',
            y='Importers',
            orientation='h',
            color='Annual growth in value between 2020-2024 (%)',
            color_continuous_scale='Oranges',
            labels={'Annual growth in value between 2020-2024 (%)': 'Annual Growth Rate (%)', 'Importers': 'Country'},
            text_auto='.1f'
        )
        fig_q2.update_layout(height=450, margin=dict(l=20, r=20, t=10, b=10))
        st.plotly_chart(fig_q2, use_container_width=True)

        st.info("💡 ** High-growth markets (Dark orange) are emerging and future markets where demand is rapidly increasing, making market penetration easier for new exporters.")

    # ------------------ TAB 3: Egypt Proximity ------------------
    with tabs[2]:
        st.subheader("Which countries already import Hydrogen Peroxide from Egypt?")
        st.markdown("Since the available data describes total imports, we have represented here the **Egypt Trade Facilitation, Geographical & Logistics Accessibility Index** based on geographical proximity and open market size.")


        if 'Egyptian exports (USD thousand)' in df_me.columns:
            export_col = 'Egyptian exports (USD thousand)'
            title_text = "Actual Egyptian Exports to ME Markets"
        else:

            df_me['Egypt Accessibility Index (Score)'] = (df_me['Value imported in 2024 (USD thousand)'] * (1 - df_me['Concentration of supplying countries'])).round(0)
            export_col = 'Egypt Accessibility Index (Score)'
            title_text = "Egypt Market Accessibility & Proximity Index"

        fig_q3 = px.bar(
            df_me.sort_values(by=export_col, ascending=True),
            x=export_col,
            y='Importers',
            orientation='h',
            color=export_col,
            color_continuous_scale='Greens',
            labels={export_col: 'Accessibility Score / Volume', 'Importers': 'Country'},
            text_auto='.2s'
        )
        fig_q3.update_layout(height=450, margin=dict(l=20, r=20, t=10, b=10))
        st.plotly_chart(fig_q3, use_container_width=True)

        st.warning("📣 Neighboring Arab markets to Egypt by land and sea in the Middle East (such as Saudi Arabia, UAE, Jordan) possess a geographical advantage that makes Egyptian shipping highly competitive compared to Asian or European suppliers.")

    # ------------------ TAB 4: Golden Targets (Multi-Criteria) ------------------
    with tabs[3]:
        st.subheader("Which markets meet at least two criteria: Top, Dynamic, or Actual?")
        st.markdown("An integrated smart filtering system to identify countries that meet two or more of the following criteria:")
        st.markdown("- **Top (Large Size):** Import value is higher than the general median.")
        st.markdown("- **Dynamic (Fast Growth):** Growth rate is higher than the general median.")
        st.markdown("- **Actual (Open Market):** Monopoly index is low and easy to penetrate due to no single country dominating.")

        golden_df = df_me[df_me['Criteria_Count'] >= 2].sort_values(by='Value imported in 2024 (USD thousand)', ascending=False)


        st.dataframe(
            golden_df[['Importers', 'Value imported in 2024 (USD thousand)', 'Annual growth in value between 2020-2024 (%)', 'Concentration of supplying countries', 'Criteria_Count']],
            column_config={
                "Importers": "Target Country",
                "Value imported in 2024 (USD thousand)": st.column_config.NumberColumn("Market Size ($K)", format="$%dK"),
                "Annual growth in value between 2020-2024 (%)": st.column_config.NumberColumn("Growth Rate", format="%d%%"),
                "Concentration of supplying countries": st.column_config.ProgressColumn("HHI Monopoly Index", min_value=0, max_value=1, format="%.2f"),
                "Criteria_Count": "Criteria Met (Score)"
            },
            use_container_width=True,
            hide_index=True
        )

        st.success(f"🏆 Found **{len(golden_df)}** promising and ideal markets for Egypt in the Middle East based on multi-criteria analysis!")

    # ------------------ TAB 5: Market Structure (HHI) ------------------
    with tabs[4]:
        st.subheader("Is the target market concentrated among a few exporters or open?")
        st.markdown("Analysis of market structure and monopoly level using the Herfindahl-Hirschman Index (HHI) for supplying countries.")


        def classify_hhi(val):
            if val >= 0.6: return "High Monopoly"
            elif val >= 0.4: return "Moderate Monopoly"
            else: return "Highly Competitive"

        df_me['Structure'] = df_me['Concentration of supplying countries'].apply(classify_hhi)

        col_left, col_right = st.columns([2, 1])

        with col_left:

            fig_q5 = px.scatter(
                df_me,
                x='Concentration of supplying countries',
                y='Value imported in 2024 (USD thousand)',
                size='Value imported in 2024 (USD thousand)',
                color='Structure',
                hover_name='Importers',
                labels={'Concentration of supplying countries': 'HHI Monopoly Index', 'Value imported in 2024 (USD thousand)': 'Market Size ($K)'},
                color_discrete_map={
                    "High Monopoly": "#ef4444",
                    "Moderate Monopoly": "#f59e0b",
                    "Highly Competitive": "#10b981"
                }
            )
            fig_q5.add_vline(x=0.6, line_dash="dash", line_color="#ef4444", annotation_text="High Monopoly Zone")
            fig_q5.add_vline(x=0.4, line_dash="dash", line_color="#f59e0b", annotation_text="Moderate Zone")
            fig_q5.update_layout(height=400, margin=dict(l=10, r=10, t=10, b=10))
            st.plotly_chart(fig_q5, use_container_width=True)

        with col_right:
            st.markdown("##### 📊 Market Structural Distribution")
            struct_counts = df_me['Structure'].value_counts().reset_index()
            fig_pie = px.pie(
                struct_counts,
                values='count',
                names='Structure',
                color_discrete_sequence=['#10b981', '#f59e0b', '#ef4444']
            )
            fig_pie.update_layout(height=300, showlegend=False, margin=dict(l=10, r=10, t=10, b=10))
            st.plotly_chart(fig_pie, use_container_width=True)
